namespace SmsWorkbench
{
    public sealed record SettingsSectionDefinition(string Title, IReadOnlyList<SettingDefinition> Fields);
    public sealed record SettingsCategoryDefinition(string Title, IReadOnlyList<SettingsSectionDefinition> Sections);

    public static class SettingsCatalog
    {
        private static SettingDefinition Text(string key, string label, string path, string fallback = "")
            => new(key, label, path, SettingFieldKind.Text, fallback);
        private static SettingDefinition Secret(string key, string label, string path)
            => new(key, label, path, SettingFieldKind.Secret);
        private static SettingDefinition Integer(string key, string label, string path, string fallback = "")
            => new(key, label, path, SettingFieldKind.Number, fallback);
        private static SettingDefinition Boolean(string key, string label, string path, bool fallback)
            => new(key, label, path, SettingFieldKind.Boolean, fallback ? "true" : "false");
        private static SettingDefinition Options(string key, string label, string path, string fallback, params string[] options)
            => new(key, label, path, SettingFieldKind.Options, fallback, options);
        private static SettingDefinition Multiline(string key, string label, string path, string fallback = "")
            => new(key, label, path, SettingFieldKind.Multiline, fallback);
        private static SettingsSectionDefinition Section(string title, params SettingDefinition[] fields) => new(title, fields);
        private static SettingsCategoryDefinition Category(string title, params SettingsSectionDefinition[] sections) => new(title, sections);

        public static IReadOnlyList<SettingsCategoryDefinition> Categories { get; } = new[]
        {
            Category("Email và nhận thư",
                Section("Pool email",
                    Integer("otp_poll_interval", "Khoảng polling OTP (giây)", "email_registration.otp_poll_interval"),
                    Text("token_file", "File pool email", "email_registration.token_file")),
                Section("ReMail",
                    Boolean("remail_enabled", "Bật", "email_registration.remail.enabled", true),
                    Text("remail_base_url", "Địa chỉ API", "email_registration.remail.base_url", "https://remail.aishop6.com"),
                    Secret("remail_api_key", "API Key", "email_registration.remail.api_key"),
                    Integer("remail_project_id", "ID dự án", "email_registration.remail.project_id", "2"),
                    Options("remail_supply", "Chiến lược tồn kho", "email_registration.remail.supply", "private_first", "private_first", "public_only"),
                    Text("remail_email_suffix", "Hậu tố email", "email_registration.remail.email_suffix", "outlook.com")),
                Section("Smailr",
                    Boolean("smailr_enabled", "Bật", "email_registration.smailr.enabled", false),
                    Text("smailr_base_url", "Địa chỉ API", "email_registration.smailr.base_url", "https://smailr.com"),
                    Secret("smailr_api_key", "API Key", "email_registration.smailr.api_key"),
                    Options("smailr_default_domain", "Tên miền email (LV1+)", "email_registration.smailr.default_domain", "smailr.com",
                        "smailr.com", "loc.cc", "mail.nodeloc.cc", "nodeloc.cc"),
                    Integer("smailr_timeout", "Timeout request (giây)", "email_registration.smailr.timeout", "30")),
                Section("CFWorker",
                    Text("cfworker_url", "Worker URL", "email_registration.cfworker_url"),
                    Text("cfworker_domain", "Tên miền email", "email_registration.cfworker_domain"),
                    Secret("cfworker_admin_token", "Admin Token", "email_registration.cfworker_admin_token"),
                    Secret("cfworker_api_token", "Cloudflare API Token", "email_registration.cfworker_api_token"))),

            Category("Đăng ký và nhận mã",
                Section("Driver đăng ký",
                    Options("registration_driver", "Driver đăng ký", "registration.driver", "protocol",
                        "protocol", "playwright", "roxy", "cloak", "camoufox", "adspower"),
                    Boolean("registration_browser_headless", "Chế độ headless trình duyệt", "registration.browser_headless", true),
                    Integer("registration_browser_timeout", "Timeout trình duyệt (giây)", "registration.browser_timeout_seconds", "90"),
                    Text("registration_browser_locale", "Ngôn ngữ trình duyệt", "registration.browser_locale", "en-US"),
                    Text("registration_browser_timezone", "Múi giờ trình duyệt", "registration.browser_timezone", "America/New_York")),
                Section("RoxyBrowser",
                    Text("roxy_api_base", "Địa chỉ API cục bộ", "registration.drivers.roxy.api_base", "http://127.0.0.1:50000"),
                    Secret("roxy_api_token", "API Token", "registration.drivers.roxy.api_token"),
                    Text("roxy_workspace_id", "ID workspace", "registration.drivers.roxy.workspace_id"),
                    Text("roxy_project_id", "ID dự án", "registration.drivers.roxy.project_id"),
                    Text("roxy_profile_id", "ID profile cố định", "registration.drivers.roxy.profile_id"),
                    Boolean("roxy_delete_profile", "Xóa profile tạm sau tác vụ", "registration.drivers.roxy.delete_profile_after_run", true),
                    Boolean("roxy_keep_browser_open", "Giữ nguyên trình duyệt", "registration.drivers.roxy.keep_browser_open", false)),
                Section("CloakBrowser",
                    Boolean("cloak_humanize", "Bật hành vi giống người dùng", "registration.drivers.cloak.humanize", true),
                    Boolean("cloak_geoip", "Khớp môi trường theo exit", "registration.drivers.cloak.geoip", true),
                    Boolean("cloak_use_proxy", "Dùng proxy đăng ký", "registration.drivers.cloak.use_proxy", true),
                    Secret("cloak_license_key", "License Key", "registration.drivers.cloak.license_key"),
                    Text("cloak_fingerprint_seed", "Seed fingerprint", "registration.drivers.cloak.fingerprint_seed"),
                    Text("cloak_user_data_dir", "Thư mục user lưu lâu dài", "registration.drivers.cloak.user_data_dir"),
                    Boolean("cloak_keep_browser_open", "Giữ nguyên trình duyệt", "registration.drivers.cloak.keep_browser_open", false)),
                Section("Camoufox",
                    Boolean("camoufox_humanize", "Bật hành vi giống người dùng", "registration.drivers.camoufox.humanize", true),
                    Boolean("camoufox_geoip", "Khớp môi trường theo exit", "registration.drivers.camoufox.geoip", true),
                    Boolean("camoufox_use_proxy", "Dùng proxy đăng ký", "registration.drivers.camoufox.use_proxy", true),
                    Integer("camoufox_max_width", "Chiều rộng màn hình tối đa", "registration.drivers.camoufox.max_width", "1280"),
                    Integer("camoufox_max_height", "Chiều cao màn hình tối đa", "registration.drivers.camoufox.max_height", "900"),
                    Text("camoufox_locale", "Ngôn ngữ trình duyệt", "registration.drivers.camoufox.locale"),
                    Text("camoufox_timezone", "Múi giờ trình duyệt", "registration.drivers.camoufox.timezone"),
                    Text("camoufox_user_data_dir", "Thư mục user lưu lâu dài", "registration.drivers.camoufox.user_data_dir"),
                    Boolean("camoufox_keep_browser_open", "Giữ nguyên trình duyệt", "registration.drivers.camoufox.keep_browser_open", false)),
                Section("AdsPower",
                    Text("adspower_api_base", "Địa chỉ API cục bộ", "registration.drivers.adspower.api_base", "http://127.0.0.1:50325"),
                    Text("adspower_user_id", "ID môi trường (user_id)", "registration.drivers.adspower.user_id"),
                    Boolean("adspower_headless", "Khởi động headless", "registration.drivers.adspower.headless", false),
                    Boolean("adspower_keep_browser_open", "Giữ nguyên trình duyệt", "registration.drivers.adspower.keep_browser_open", false)),
                Section("SMSBower",
                    Secret("smsbower_api_key", "SMSBower API Key", "phone_reuse.smsbower.api_key"),
                    Integer("smsbower_sms_timeout", "Thời gian chờ SMS (giây)", "phone_reuse.smsbower.sms_timeout"),
                    Integer("smsbower_sms_poll_interval", "Khoảng polling SMS (giây)", "phone_reuse.smsbower.sms_poll_interval"),
                    Integer("phone_max_reuse_count", "Số lần tái sử dụng", "phone_reuse.max_reuse_count"),
                    Integer("phone_send_cooldown_seconds", "Cooldown gửi mã (giây)", "phone_reuse.send_cooldown_seconds"),
                    Integer("phone_send_retry_attempts", "Số lần thử gửi lại mã", "phone_reuse.send_retry_attempts"),
                    Integer("phone_send_retry_delay_seconds", "Độ trễ thử gửi lại mã (giây)", "phone_reuse.send_retry_delay_seconds"),
                    Text("phone_state_file", "File trạng thái", "phone_reuse.state_file")),
                Section("Codex OAuth",
                    Integer("codex_registration_timeout", "Timeout OAuth (giây)", "codex_oauth.registration_timeout"),
                    Boolean("codex_allow_passwordless_takeover", "Cho phép fallback OTP email", "codex_oauth.allow_passwordless_takeover", false),
                    Boolean("codex_auto_phone_verification", "Tự xác minh điện thoại", "codex_oauth.auto_phone_verification", false),
                    Boolean("codex_require_registration_refresh_token", "Đăng ký yêu cầu RT", "codex_oauth.require_registration_refresh_token", true),
                    Boolean("codex_require_registration_phone_verification", "Đăng ký yêu cầu số điện thoại", "codex_oauth.require_registration_phone_verification", true)),
                Section("Lưu AT ổn định",
                    Integer("registration_at_stability_probe_count", "Số lần kiểm tra AT", "registration.at_stability_probe_count", "2"),
                    Integer("registration_at_stability_probe_delay", "Khoảng kiểm tra (giây)", "registration.at_stability_probe_delay_seconds", "10"),
                    Integer("registration_at_probe_timeout", "Timeout mỗi lần kiểm tra (giây)", "registration.at_probe_timeout_seconds", "30")),
                Section("Song song theo giai đoạn",
                    Integer("registration_auth_concurrency", "Luồng xác thực song song", "registration.stage_concurrency.auth", "1"),
                    Integer("registration_network_concurrency", "Mạng đăng ký song song", "registration.stage_concurrency.network", "4"),
                    Integer("registration_at_probe_concurrency", "Kiểm tra AT song song", "registration.stage_concurrency.at_probe", "4")),
                Section("Lập lịch theo đợt",
                    Boolean("pulse_enabled", "Bật lập lịch theo đợt", "registration.pulse.enabled", false),
                    Integer("pulse_wave_size", "Số tài khoản mỗi đợt", "registration.pulse.wave_size", "4"),
                    Integer("pulse_wave_delay", "Khoảng giữa các đợt (giây)", "registration.pulse.wave_delay_seconds", "5"),
                    Integer("pulse_ban_threshold", "Ngưỡng khóa OTP", "registration.pulse.ban_threshold", "2"),
                    Integer("pulse_ban_pause", "Tạm dừng khi bị khóa (giây)", "registration.pulse.ban_pause_seconds", "60"),
                    Integer("pulse_max_waves", "Số đợt tối đa (0=không giới hạn)", "registration.pulse.max_waves", "0")),
                Section("Pool tiến trình trình duyệt",
                    Boolean("browser_pool_enabled", "Bật pool tiến trình", "registration.browser_process_pool.enabled", false),
                    Integer("browser_pool_max_concurrent", "Số trình duyệt song song tối đa", "registration.browser_process_pool.max_concurrent", "4"),
                    Integer("browser_pool_max_uses", "Số lần tái sử dụng tối đa mỗi tiến trình", "registration.browser_process_pool.max_uses_per_process", "10"),
                    Boolean("browser_pool_recycle_on_error", "Thu hồi tiến trình khi lỗi", "registration.browser_process_pool.recycle_on_error", true)),
                Section("Sentinel",
                    Text("sentinel_version", "Phiên bản Sentinel", "email_registration.sentinel_version"),
                    Integer("sentinel_max_concurrency", "Trích xuất song song", "email_registration.sentinel_max_concurrency", "2"),
                    Integer("sentinel_prewarm_window", "Cửa sổ prewarm 1-1", "email_registration.sentinel_prewarm_window", "4"),
                    Integer("sentinel_circuit_failures", "Số lỗi trước khi ngắt mạch", "email_registration.sentinel_circuit_failures", "3"),
                    Integer("sentinel_circuit_cooldown", "Cooldown ngắt mạch (giây)", "email_registration.sentinel_circuit_cooldown_seconds", "60"))),

            Category("Nhập và tài khoản",
                Section("CPA",
                    Text("cpa_api_url", "Địa chỉ CPA", "cpa_mode.api_url"),
                    Secret("cpa_api_token", "CPA Token", "cpa_mode.api_token")),
                Section("SUB2API",
                    Text("sub2api_url", "Địa chỉ API", "sub2api.api_url"),
                    Secret("sub2api_token", "API Token", "sub2api.api_token"),
                    Text("sub2api_email", "Email đăng nhập", "sub2api.email"),
                    Secret("sub2api_password", "Mật khẩu đăng nhập", "sub2api.password"),
                    Text("sub2api_group", "Nhóm đích", "sub2api.group_name"),
                    Text("sub2api_group_ids", "ID nhóm", "sub2api.group_ids"),
                    Text("sub2api_proxy", "Proxy từ xa", "sub2api.proxy_name"),
                    Text("sub2api_proxy_id", "ID proxy", "sub2api.proxy_id"),
                    Integer("sub2api_priority", "Ưu tiên", "sub2api.priority"),
                    Integer("sub2api_concurrency", "Tài khoản song song", "sub2api.concurrency"),
                    Options("sub2api_auth_mode", "Chế độ thông tin đăng nhập", "sub2api.auth_mode", "auto", "auto", "oauth", "agent_identity"),
                    Boolean("sub2api_verify_after_import", "Kiểm tra kết nối sau khi nhập", "sub2api.verify_after_import", true))),

            Category("Mạng và thanh toán",
                Section("Mạng cơ bản",
                    Text("registration_proxy", "Proxy đăng ký (chính, hỗ trợ host:port:user:password / http / socks5 / socks5h)", ""),
                    Multiline("registration_proxy_pool", "Pool proxy đăng ký (hỗ trợ host:port:user:password / http / socks5 / socks5h)", ""),
                    Text("mailbox_proxy", "Proxy nhận email", "")),
                Section("Quản lý giao thức",
                    Text("protocol_enabled_methods", "Phương thức bật", "", "paypal,gopay,gcash,grabpay,upi,ideal,pix,kakao,blik,twint,direct_card,momo"),
                    Text("protocol_reference_root", "Thư mục trích link", "protocol_payments.reference_root", "services/protocol-payment"),
                    Text("protocol_state_file", "File trạng thái", "protocol_payments.state_file", "runtime/payment_link_runs.jsonl"),
                    Integer("protocol_timeout_seconds", "Timeout giao thức (giây)", "protocol_payments.timeout_seconds", "900")),
                Section("Thanh toán hàng loạt chính thức",
                    Integer("protocol_batch_momo_workers", "MoMo song song", "protocol_payments.batch.method_workers.momo", "2"),
                    Integer("protocol_batch_kakao_workers", "Kakao song song", "protocol_payments.batch.method_workers.kakao", "2"),
                    Integer("protocol_batch_gopay_workers", "GoPay song song", "protocol_payments.batch.method_workers.gopay", "2"),
                    Integer("protocol_batch_gcash_workers", "GCash song song", "protocol_payments.batch.method_workers.gcash", "2"),
                    Integer("protocol_batch_grabpay_workers", "GrabPay song song", "protocol_payments.batch.method_workers.grabpay", "2"),
                    Boolean("protocol_batch_pause_on_canary_failure", "Tạm dừng khi canary lỗi", "protocol_payments.batch.pause_on_canary_failure", true),
                    Integer("protocol_batch_canary_pause_seconds", "Số giây tạm dừng", "protocol_payments.batch.canary_pause_seconds", "21600"),
                    Multiline("protocol_payment_matrix", "JSON ma trận đủ điều kiện khu vực", "")),
                Section("PayPal",
                    Multiline("paypal_proxy", "Pool proxy PayPal", ""),
                    Options("paypal_billing_region", "Khu vực tạo đơn", "", "DE", "JP", "US", "AU", "DE", "FR", "GB", "IN", "BR"),
                    Options("paypal_link_generation_type", "Chế độ tạo link trực tiếp PayPal", "paypal.link_generation_type", "hosted_long_url", "hosted_long_url", "paypal_direct", "paypal_direct_zero_due"))),

            Category("Dữ liệu và file",
                Section("Môi trường chạy",
                    Text("python_path", "Đường dẫn Python interpreter", "runtime.python_path", "python")),
                Section("Lưu trữ cục bộ",
                    Text("output_directory", "Thư mục Session", "output.directory"),
                    Text("sqlite_path", "Đường dẫn SQLite", "storage.sqlite_path")))
        };

        public static IEnumerable<SettingDefinition> AllFields => Categories.SelectMany(category => category.Sections).SelectMany(section => section.Fields);
    }
}
